# terraform/inventory.tpl
#
# This file is a template used by Terraform to generate the Ansible inventory.
# DO NOT EDIT THIS FILE DIRECTLY.

[all:vars]
# Update the ansible_user based on your chosen AMI.
# 'ec2-user' is common for RHEL on AWS.
# 'core' is used for Red Hat CoreOS (RHCOS).
ansible_user = "ec2-user"
ansible_python_interpreter = /usr/bin/python3

# -----------------------------------------------------------------------------
# OpenShift Node Groups
# -----------------------------------------------------------------------------
[controllers]
%{ for instance in controllers ~}
${instance.private_ip}
%{ endfor ~}

[infra_nodes]
%{ for instance in infra ~}
${instance.private_ip}
%{ endfor ~}

[worker_nodes]
%{ for instance in workers ~}
${instance.private_ip}
%{ endfor ~}

# -----------------------------------------------------------------------------
# Ansible Parent Groups
# -----------------------------------------------------------------------------

# A group for all nodes in the cluster
[ocp_cluster:children]
controllers
infra_nodes
worker_nodes

# A group for all nodes that run the 'worker' ignition config
[ocp_workers_all:children]
infra_nodes
worker_nodes