- name: Create installation directory
  ansible.builtin.file:
    path: "{{ ocp_install_dir }}"
    state: directory
    mode: '0755'

- name: Download OpenShift installer
  ansible.builtin.unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    include: ["openshift-install"]
    extra_opts: [--strip-components=0]
    mode: '0755'
    creates: /usr/local/bin/openshift-install

- name: Download OpenShift client
  ansible.builtin.unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux.tar.gz"
    dest: "/usr/local/bin"
    remote_src: true
    include: ["oc"]
    extra_opts: [--strip-components=0]
    mode: '0755'
    creates: /usr/local/bin/oc
